#!/usr/bin/env python3

import sys
import requests

host = 'localhost'
port = '5000'

if __name__ == '__main__':
    sentence = ' '.join(sys.argv[1:])

    query = {'s': sentence}

    r = requests.post('http://' + host + ':' + port + '/interpret', json=query)
    if not r:
        sys.stderr.write('Error receiving response from server.\n')
        sys.exit(1)

    response = r.json()

    if 'parse' in response:
        print('Parse:')
        print(response['parse'])

    if 'interpret' in response:
        print('Interpret:')
        print(response['interpret'])

    if 'graph' in response:
        print('Proof graph URL:')
        print(response['graph'])

    if 'error' in response:
        print('Error:')
        print(response['error'])
